#!/bin/sh
set -eu

fail() {
    printf 'FAIL: %s\n' "$1" >&2
    exit 1
}

require_file() {
    [ -s "$1" ] || fail "missing or empty file: $1"
}

require_text() {
    file="$1"
    pattern="$2"
    label="$3"
    grep -Fq -- "$pattern" "$file" || fail "$label missing in $file"
}

reject_text() {
    pattern="$1"
    label="$2"
    if grep -RInE "$pattern" README.md README.ko.md agents docs templates examples 2>/dev/null; then
        fail "$label"
    fi
}

require_file agents/novelist.md
require_file agents/novelist-writer.md
require_file agents/novelist-editor.md
require_file agents/novelist-loremaster.md
require_file agents/novelist-otaku.md
require_file skills/setting-collapse-detector/SKILL.md
require_file templates/style-guide.md
require_file templates/character-sheet.md
require_file templates/item-sheet.md
require_file templates/location-sheet.md
require_file templates/world-rule-sheet.md
require_file templates/series-bible.md
require_file templates/narrative-state.md
require_file templates/writing-session.md
require_file templates/verification-manifest.md
require_file templates/verification-evidence.md
require_file templates/retcon-proposal.md
require_file examples/production-continuity-scenario.md
require_file examples/style-character-drift-scenario.md
require_file examples/sample-work/series-bible.md
require_file examples/sample-work/settings/items/brass-witness-key.md
require_file examples/sample-work/settings/locations/lower-archive-corridor.md
require_file examples/sample-work/volume-1/verification-reports/chapter-01.md
require_file examples/sample-work/volume-1/writing-session.md
require_file docs/production-readiness-audit.md
require_file docs/model-recommendations.md
require_file docs/model-recommendations.ko.md
require_file scripts/validate-continuity-scenario.sh
require_file scripts/validate-style-character-drift-scenario.sh
require_file scripts/validate-sample-work.sh
require_file scripts/validate-verification-manifest.sh
require_file scripts/test-verification-manifest-negative.sh
require_file scripts/validate-production-artifacts.sh
require_file scripts/test-production-artifacts-negative.sh
require_file scripts/validate-agent-frontmatter.sh
require_file scripts/smoke-install.sh
require_file scripts/validate-all.sh
require_file Makefile
require_file .github/workflows/validate.yml

if grep -nE 'EPUB로 만들어|출판|패키징|프랜차이즈|작품|권|어투|장면|설정|사용자|검증' README.md; then
    fail "Korean prose remains in English README.md"
fi

if grep -nE '^#{1,3} .*\([A-Za-z][A-Za-z /&-]*\)' README.ko.md; then
    fail "English parenthetical heading remains in Korean README.ko.md"
fi

for file in agents/*.md; do
    first_line="$(sed -n '1p' "$file")"
    [ "$first_line" = "---" ] || fail "agent frontmatter delimiter missing: $file"
    require_text "$file" "permission:" "permission block"
done

require_text agents/novelist.md "Prose Baseline: elegant, controlled, and assured literary prose by a renowned, seasoned professional novelist" "router default prose baseline"
require_text agents/novelist.md "Draft Pipeline" "router draft pipeline"
require_text agents/novelist.md "Build Pipeline" "router build pipeline"
require_text agents/novelist.md "Do not build EPUB output unless" "router no automatic EPUB build"
require_text agents/novelist.md "Draft Pipeline only" "router writing routes to draft only"
require_text agents/novelist.md "Writing and revision work must be sequential, never parallel" "router no parallel writing/revision"
require_text agents/novelist.md "Do not run Writer, Editor, or Otaku calls for multiple beats, paragraphs, chapters, or editable spans at the same time" "router no parallel manuscript agents"
require_text agents/novelist.md "Parallel work is allowed only for independent read-only context gathering" "router parallel limited to read-only gathering"
require_text agents/novelist.md "Non-Negotiable Pipeline Completion Gate" "router non-negotiable pipeline gate"
require_text agents/novelist.md "Never skip, merge, compress, summarize, simulate, or retroactively claim any required pipeline step" "router shortcut prevention"
require_text agents/novelist.md "Pipeline Step Ledger" "router pipeline step ledger"
require_text agents/novelist.md "Pipeline Completion Audit" "router pipeline completion audit"
require_text agents/novelist.md "If the audit fails, do not deliver the work as complete" "router incomplete audit block"
require_text agents/novelist.md "Requested Scope of Work" "router requested scope recording"
require_text agents/novelist.md "Completion Target" "router completion target recording"
require_text agents/novelist.md "Do not stop merely because one beat, one paragraph, one scene, or one intermediate pass is complete" "router no intermediate stopping"
require_text agents/novelist.md "Seed-to-Fruit Narrative Growth Pipeline" "router seed-to-fruit pipeline"
require_text agents/novelist.md "Macro Skeleton" "router macro skeleton"
require_text agents/novelist.md "Execution Unit Queue" "router execution unit queue"
require_text agents/novelist.md "Skeleton Drift Check" "router skeleton drift check"
require_text agents/novelist.md "Do not halt only because the user has not supplied a large-scale outline" "router authors missing macro skeleton"
require_text agents/novelist.md "Revision requests must also run sequentially" "router sequential revision"
require_text agents/novelist.md "Never use it for Writer, Editor, Otaku verification, manuscript edits, ledger updates, manifest updates, or commits" "router parallel skill restriction"
require_text README.md "Writing and revision steps are intentionally sequential, not parallel" "readme no parallel writing/revision"
require_text README.md "Model Recommendations" "README model recommendations link"
require_text README.md "The pipeline is non-negotiable" "readme non-negotiable pipeline gate"
require_text README.md "Pipeline Completion Audit" "readme pipeline completion audit"
require_text README.md "The user's initial request defines the completion target" "readme initial request completion target"
require_text README.md "Scope-Complete Execution" "readme scope-complete execution"
require_text README.md "Seed-to-Fruit Narrative Growth" "readme seed-to-fruit narrative growth"
require_text README.md "Agent-Authored Macro Skeleton" "readme agent-authored macro skeleton"
require_text README.md "Editor Micro Focus" "readme editor micro focus"
require_text README.md "Otaku Branch Traversal Audit" "readme otaku branch traversal audit"
require_text README.md "Skeleton Drift Check" "readme skeleton drift check"
require_text README.ko.md "집필과 수정 단계는 의도적으로 순차 실행하며 병렬 실행하지 않습니다" "korean readme no parallel writing/revision"
require_text README.ko.md "model-recommendations.ko.md" "Korean README model recommendations link"
require_text README.ko.md "파이프라인은 협상 대상이 아닙니다" "korean readme non-negotiable pipeline gate"
require_text README.ko.md "파이프라인 완료 감사" "korean readme pipeline completion audit"
require_text README.ko.md "사용자의 최초 요청이 완료 목표를 정의합니다" "korean readme initial request completion target"
require_text README.ko.md "요청 범위 완료 실행" "korean readme scope-complete execution"
require_text README.ko.md "씨앗-열매 서사 성장" "korean readme seed-to-fruit narrative growth"
require_text README.ko.md "에이전트 작성 Macro Skeleton" "korean readme agent-authored macro skeleton"
require_text README.ko.md "편집자 미시 집중" "korean readme editor micro focus"
require_text README.ko.md "설정 검증가 가지 진행 감사" "korean readme otaku branch traversal audit"
require_text README.ko.md "Skeleton Drift Check" "korean readme skeleton drift check"
require_text docs/agent-design.md "Drafting and revision are strictly sequential" "design no parallel drafting/revision"
require_text docs/agent-design.md "Model Recommendations" "design model recommendations link"
require_text docs/agent-design.md "model-recommendations.ko.md" "design Korean model recommendations link"
require_text docs/agent-design.md "The pipeline is treated as a mandatory production contract" "design mandatory pipeline contract"
require_text docs/agent-design.md "Non-Negotiable Pipeline Completion Gate" "design non-negotiable pipeline gate"
require_text docs/agent-design.md "The initial user request defines the completion target" "design initial request completion target"
require_text docs/agent-design.md "Scope-Complete Execution" "design scope-complete execution"
require_text docs/agent-design.md "Seed-to-Fruit Narrative Growth" "design seed-to-fruit narrative growth"
require_text docs/agent-design.md "Agent-Authored Macro Skeleton" "design agent-authored macro skeleton"
require_text docs/agent-design.md "Editor Micro Focus" "design editor micro focus"
require_text docs/agent-design.md "Otaku Branch Traversal Audit" "design otaku branch traversal audit"
require_text docs/agent-design.md "Skeleton Drift Check" "design skeleton drift check"
require_text docs/agent-design.md "Parallel read-only context gathering only" "design parallel skill read-only restriction"
require_text docs/agent-design.md "It is not used for Writer, Editor, Otaku verification, manuscript edits, ledger updates, manifest updates, or commits" "design parallel skill manuscript restriction"
require_text agents/novelist.md "The project root is always the Franchise root" "router franchise root is not work"
require_text agents/novelist.md 'Do not treat a root-level `series-bible.md` as an active Work' "router rejects root series bible work"
require_text agents/novelist.md "epub-src/" "router editable EPUB source"
require_text agents/novelist.md "Style Contract" "router style contract propagation"
require_text agents/novelist.md "Character Voice Matrix" "router character voice matrix propagation"
require_text agents/novelist.md "narrative-state.md" "router continuity ledger"
require_text agents/novelist.md "verification-manifest.md" "router verification manifest"
require_text agents/novelist.md "writing-session.md" "router writing session checkpoint"
require_text agents/novelist.md "Interruption Recovery & Resume Gate" "router resume gate"
require_text agents/novelist.md "Operation Type" "router session operation type"
require_text agents/novelist.md "Temporary Work Isolation" "router temporary work isolation"
require_text agents/novelist.md "Resume Validation" "router resume validation"
require_text agents/novelist.md "Locked Before Context SHA256" "router revision locked before context hash"
require_text agents/novelist.md "Locked After Context SHA256" "router revision locked after context hash"
require_text agents/novelist.md ".session/current-work.md" "router temporary session work file"
require_text agents/novelist.md "Draft SHA256" "router draft hash manifest recording"
require_text agents/novelist.md "Canon Snapshot SHA256" "router canon hash manifest recording"
require_text agents/novelist.md "Verification Evidence" "router verification evidence recording"
require_text agents/novelist.md "Style Drift Audit: PASS" "router style audit manifest recording"
require_text agents/novelist.md "Character Voice Audit: PASS" "router voice audit manifest recording"
require_text agents/novelist.md "Artifact Preflight Gate" "router artifact preflight gate"
require_text agents/novelist.md "scripts/validate-production-artifacts.sh" "router production artifact validator"
require_text agents/novelist.md "do not draft" "router no drafting on preflight failure"
require_text agents/novelist.md "Inventory Canon References" "router inventory canon references"
require_text agents/novelist.md "Location / World Canon References" "router location world canon references"
require_text agents/novelist.md "templates/style-guide.md" "router template scaffold reference"
require_text agents/novelist.md "templates/writing-session.md" "router writing session template reference"
require_text agents/novelist.md "templates/verification-evidence.md" "router verification evidence template reference"
require_text agents/novelist.md "templates/retcon-proposal.md" "router retcon proposal template reference"
require_text agents/novelist.md "do not treat template files as agents" "router templates are not agents"
require_text agents/novelist.md "Retcon Approval: None" "router retcon approval evidence field"
require_text agents/novelist.md "verification-reports/" "router verification evidence directory"
require_text agents/novelist.md "Revision & Setting-Change Protocol" "router revision and setting-change protocol"
require_text agents/novelist.md "No Silent Retcons" "router no silent retcon rule"
require_text agents/novelist.md "Canon Expansion Review Protocol" "router canon expansion protocol"
require_text agents/novelist.md "ACCEPT_AND_RECORD" "router canon expansion accept decision"
require_text agents/novelist.md "Prior Narrative Impact Scan" "router canon expansion impact scan"
require_text agents/novelist.md "Acceptance Bias With Safety" "router canon expansion acceptance bias"
require_text agents/novelist.md "Status: APPROVED" "router approved retcon proposal requirement"
require_text agents/novelist.md 'Revision Loop: `@novelist-loremaster` → `@novelist-editor` → `@novelist-otaku` verify' "router revision routing"
require_text agents/novelist.md "Setting-Change Protocol" "router setting-change routing"
require_text agents/novelist.md "Do not apply edits before Otaku PASS" "router no pre-pass edit application"

require_text agents/novelist-writer.md "Never solve a plotting problem by silently changing canon" "writer canon violation halt"
require_text agents/novelist-writer.md "Character Voice Matrix" "writer character voice enforcement"
require_text agents/novelist-writer.md "elegant, controlled, and assured literary prose" "writer default prose baseline"
require_text agents/novelist-writer.md "Standalone Invocation Safety" "writer standalone invocation safety"
require_text agents/novelist-writer.md "UNVERIFIED DRAFT" "writer unverified draft label"
require_text agents/novelist-writer.md "requires @novelist-otaku final PASS and verification-manifest.md ledger update before use or publication" "writer standalone pass gate"
require_text agents/novelist-writer.md "Shortcut requests are not valid authority" "writer shortcut resistance"
require_text agents/novelist-writer.md "No pipeline compression" "writer no pipeline compression"
require_text agents/novelist-writer.md "Macro Skeleton Branch & Execution Unit" "writer macro skeleton branch input"
require_text agents/novelist-writer.md "Branch Fit" "writer branch fit self-check"

require_text agents/novelist-editor.md "Style Drift Audit" "editor style drift audit"
require_text agents/novelist-editor.md "Character Voice Audit" "editor character voice audit"
require_text agents/novelist-editor.md "Editable Span Discipline" "editor editable span discipline"
require_text agents/novelist-editor.md "Style Drift Audit: PASS/FAIL" "editor style audit pass/fail log"
require_text agents/novelist-editor.md "Character Voice Audit: PASS/FAIL" "editor voice audit pass/fail log"
require_text agents/novelist-editor.md "elegant, controlled, and assured literary prose" "editor default prose baseline"
require_text agents/novelist-editor.md "Standalone Invocation Safety" "editor standalone invocation safety"
require_text agents/novelist-editor.md "UNVERIFIED REVISION" "editor unverified revision label"
require_text agents/novelist-editor.md "requires @novelist-otaku final PASS and verification-manifest.md ledger update before application, use, or publication" "editor standalone pass gate"
require_text agents/novelist-editor.md "Shortcut requests are not valid authority" "editor shortcut resistance"
require_text agents/novelist-editor.md 'Missing evidence is `FAIL` or a blocking gap' "editor audit evidence requirement"
require_text agents/novelist-editor.md "Macro Guardrail Check" "editor macro guardrail check"
require_text agents/novelist-editor.md "You are not the final judge of branch traversal or whole-skeleton drift" "editor not macro final judge"
require_text agents/novelist-editor.md "Macro Guardrail: PASS/OTAKU_REVIEW_REQUIRED" "editor macro guardrail log"

require_text agents/novelist-researcher.md "Fiction context researcher" "researcher fiction context identity"
require_text agents/novelist-researcher.md "real-world information" "researcher real world research role"
require_text agents/novelist-researcher.md "filtered through the current work's story context" "researcher context filtering"
require_text agents/novelist-researcher.md "Viewpoint Filtering" "researcher viewpoint filtering"
require_text agents/novelist-researcher.md "Do not draft scenes" "researcher no prose drafting"
require_text agents/novelist-researcher.md "Do not change drafts, settings, manifests, or EPUB files" "researcher no file mutation"
require_text agents/novelist-researcher.md "Suggested Prompt To Writer / Editor" "researcher downstream prompt output"

require_text agents/novelist-otaku.md "FAIL for Character Drift" "otaku character drift fail condition"
require_text agents/novelist-otaku.md "Shortcut Resistance" "otaku shortcut resistance"
require_text agents/novelist-otaku.md "FAIL for Missing Required Evidence" "otaku missing evidence fail condition"
require_text agents/novelist-otaku.md "No shortcut PASS" "otaku no shortcut pass"
require_text agents/novelist-otaku.md "Branch Traversal / Skeleton Drift" "otaku branch traversal skeleton drift check"
require_text agents/novelist-otaku.md "Branch Traversal Audit" "otaku branch traversal audit"
require_text agents/novelist-otaku.md "No macro blind spots" "otaku no macro blind spots"
require_text agents/novelist-otaku.md "SKELETON_DRIFT_REVIEW" "otaku skeleton drift review verdict"
require_text agents/novelist-otaku.md "FAIL for Ledger Contradiction" "otaku ledger contradiction fail condition"
require_text agents/novelist-otaku.md "FAIL for Unsafe Revision Span" "otaku unsafe revision span fail condition"
require_text agents/novelist-otaku.md "New Setting Candidates" "otaku new setting candidates"
require_text agents/novelist-otaku.md "CANON_EXPANSION_REVIEW" "otaku canon expansion review verdict"
require_text agents/novelist-otaku.md "ACCEPT_PENDING_IMPACT_SCAN" "otaku accept pending impact scan"
require_text agents/novelist-otaku.md "Prefer enriching canon when safe" "otaku canon expansion acceptance bias"
require_text agents/novelist-otaku.md "Required Ledger Updates After PASS" "otaku ledger update output"
require_text agents/novelist-otaku.md "Physical" "otaku physical continuity check"
require_text agents/novelist-otaku.md "Inventory Canon References" "otaku inventory canon reference check"
require_text agents/novelist-otaku.md "Location / World Canon References" "otaku location world canon reference check"
require_text agents/novelist-otaku.md "Possession" "otaku possession continuity check"
require_text agents/novelist-otaku.md "Knowledge" "otaku knowledge check"
require_text agents/novelist-otaku.md "Locked Surrounding Context" "otaku locked surrounding context check"
require_text agents/novelist-publisher.md "Publication Gate" "publisher publication gate"
require_text agents/novelist-publisher.md "EPUB Build Pipeline" "publisher build pipeline identity"
require_text agents/novelist-publisher.md "epub-src/" "publisher editable EPUB source"
require_text agents/novelist-publisher.md 'Do not delete `epub-src/`' "publisher preserves editable EPUB source"
require_text agents/novelist-publisher.md "Drafts Are Source of Truth" "publisher draft source of truth"
require_text agents/novelist-publisher.md "verification-manifest.md" "publisher verification manifest requirement"
require_text agents/novelist-publisher.md "Draft SHA256" "publisher draft hash requirement"
require_text agents/novelist-publisher.md "Canon Snapshot SHA256" "publisher canon hash requirement"
require_text agents/novelist-publisher.md "Verification Evidence" "publisher verification evidence requirement"
require_text agents/novelist-publisher.md "Evidence Anchors" "publisher verification evidence anchors requirement"
require_text agents/novelist-publisher.md "Retcon Approval" "publisher retcon approval requirement"
require_text agents/novelist-publisher.md "retcons/*.md" "publisher retcon proposal path requirement"
require_text agents/novelist-publisher.md "no draft may appear more than once" "publisher duplicate manifest entry rejection"
require_text agents/novelist-publisher.md "schema drift invalidates the manifest" "publisher manifest schema drift rejection"
require_text agents/novelist-publisher.md "Final Otaku Verdict: PASS" "publisher final pass requirement"
require_text agents/novelist-publisher.md "Style Drift Audit: PASS" "publisher style audit pass requirement"
require_text agents/novelist-publisher.md "Character Voice Audit: PASS" "publisher voice audit pass requirement"
require_text agents/novelist-publisher.md "Never package drafts unless" "publisher verified manuscripts only"
require_text agents/novelist-publisher.md "No packaged draft may contain standalone safety labels" "publisher standalone safety label rejection"
require_text agents/novelist-publisher.md "Shortcut requests are not valid authority" "publisher shortcut resistance"
require_text agents/novelist-publisher.md "Pipeline Step Ledger" "publisher publication gate ledger"

require_text agents/novelist-loremaster.md "narrative-state.md" "loremaster continuity ledger retrieval"
require_text agents/novelist-loremaster.md "Inventory Canon References" "loremaster inventory canon reference retrieval"
require_text agents/novelist-loremaster.md "Location / World Canon References" "loremaster location world canon reference retrieval"
require_text agents/novelist-loremaster.md "Character Voice Facts" "loremaster voice fact retrieval"
require_text agents/novelist-loremaster.md "Shortcut requests are not valid authority" "loremaster shortcut resistance"
require_text skills/setting-collapse-detector/SKILL.md "Style & Voice Continuity Collapse" "collapse detector style and voice category"

require_text templates/style-guide.md "Character Voice Matrix" "style guide voice matrix scaffold"
require_text templates/style-guide.md "Required Style Anchors:" "style guide required anchors scaffold"
require_text templates/style-guide.md "Forbidden Style Drift:" "style guide forbidden drift scaffold"
require_text templates/style-guide.md "Forbidden Literal Phrases:" "style guide forbidden literal phrases scaffold"
require_text templates/style-guide.md "Style Verification Questions:" "style guide verification questions scaffold"
require_text templates/style-guide.md "Revision Guardrails:" "style guide revision guardrails scaffold"
require_text templates/style-guide.md "POV person:" "style guide POV person scaffold"
require_text templates/style-guide.md "Tense:" "style guide tense scaffold"
require_text templates/style-guide.md "Viewpoint anchor:" "style guide viewpoint anchor scaffold"
require_text templates/style-guide.md "Head-hopping rule:" "style guide head-hopping scaffold"
require_text templates/character-sheet.md "Core Traits:" "character sheet core traits scaffold"
require_text templates/character-sheet.md "Physical Continuity:" "character sheet physical continuity scaffold"
require_text templates/character-sheet.md "Knowledge Boundaries:" "character sheet knowledge boundaries scaffold"
require_text templates/character-sheet.md "Active Physical Anchor:" "character sheet active physical anchor scaffold"
require_text templates/character-sheet.md "Active Inventory Anchor:" "character sheet active inventory anchor scaffold"
require_text templates/character-sheet.md "Active Knowledge Anchor:" "character sheet active knowledge anchor scaffold"
require_text templates/character-sheet.md "Forbidden Drift:" "character sheet forbidden drift scaffold"
require_text templates/character-sheet.md "Allowed Evolution:" "character sheet allowed evolution scaffold"
require_text templates/item-sheet.md "Limitations:" "item sheet limitations scaffold"
require_text templates/item-sheet.md "Active State Anchors:" "item sheet active state anchors scaffold"
require_text templates/item-sheet.md "Transfer Rules:" "item sheet transfer rules scaffold"
require_text templates/item-sheet.md "Continuity Risks:" "item sheet continuity risks scaffold"
require_text templates/location-sheet.md "Active Constraints:" "location sheet active constraints scaffold"
require_text templates/location-sheet.md "Active State Anchors:" "location sheet active state anchors scaffold"
require_text templates/location-sheet.md "Related World Rules:" "location sheet related world rules scaffold"
require_text templates/location-sheet.md "Continuity Risks:" "location sheet continuity risks scaffold"
require_text templates/world-rule-sheet.md "World Rule:" "world rule sheet statement scaffold"
require_text templates/world-rule-sheet.md "Evidence Requirements:" "world rule sheet evidence requirements scaffold"
require_text templates/world-rule-sheet.md "Active State Anchors:" "world rule sheet active state anchors scaffold"
require_text templates/world-rule-sheet.md "Continuity Risks:" "world rule sheet continuity risks scaffold"
require_text templates/narrative-state.md "Locked Prefix Summary" "narrative state locked prefix scaffold"
require_text templates/narrative-state.md "Location / World Canon References" "narrative state location world reference scaffold"
require_text templates/narrative-state.md "Inventory Canon References" "narrative state inventory reference scaffold"
require_text templates/series-bible.md "Character Evolution Log" "series bible evolution scaffold"
require_text templates/writing-session.md "Session Identity" "writing session identity scaffold"
require_text templates/writing-session.md "Operation Type:" "writing session operation type scaffold"
require_text templates/writing-session.md "Requested Scope of Work:" "writing session requested scope scaffold"
require_text templates/writing-session.md "Completion Target:" "writing session completion target scaffold"
require_text templates/writing-session.md "Seed Summary:" "writing session seed summary scaffold"
require_text templates/writing-session.md "Macro Skeleton Reference:" "writing session macro skeleton reference scaffold"
require_text templates/writing-session.md "Recovery Contract" "writing session recovery contract scaffold"
require_text templates/writing-session.md "Macro Skeleton" "writing session macro skeleton scaffold"
require_text templates/writing-session.md "Execution Unit Queue" "writing session execution unit queue scaffold"
require_text templates/writing-session.md "Skeleton Drift Log" "writing session skeleton drift log scaffold"
require_text templates/writing-session.md "Pipeline Step Ledger" "writing session pipeline step ledger scaffold"
require_text templates/writing-session.md "every mandatory step for the active route must have concrete evidence" "writing session concrete step evidence rule"
require_text templates/writing-session.md 'Status` cannot be set to `COMPLETED` until the Requested Scope of Work and Completion Target are satisfied' "writing session scope completion rule"
require_text templates/writing-session.md "do not start leaf drafting until the Macro Skeleton and Execution Unit Queue exist" "writing session growth rule"
require_text templates/writing-session.md "Last Verified Draft SHA256" "writing session draft hash scaffold"
require_text templates/writing-session.md "Last Verified Canon Snapshot SHA256" "writing session canon hash scaffold"
require_text templates/writing-session.md "Locked Before Context SHA256" "writing session locked before context scaffold"
require_text templates/writing-session.md "Locked After Context SHA256" "writing session locked after context scaffold"
require_text templates/writing-session.md 'Temporary Work File: `.session/current-work.md`' "writing session temp work scaffold"
require_text templates/writing-session.md "Resume Checklist" "writing session resume checklist scaffold"
require_text templates/verification-manifest.md "Publication Gate" "verification manifest publication gate scaffold"
require_text templates/verification-manifest.md "Draft SHA256" "verification manifest draft hash scaffold"
require_text templates/verification-manifest.md "Canon Snapshot SHA256" "verification manifest canon hash scaffold"
require_text templates/verification-manifest.md "Each packaged draft must appear exactly once" "verification manifest duplicate guard scaffold"
require_text templates/verification-manifest.md "exact column order" "verification manifest schema order guard scaffold"
require_text templates/verification-manifest.md "Style Drift Audit" "verification manifest style audit scaffold"
require_text templates/verification-manifest.md "Character Voice Audit" "verification manifest voice audit scaffold"
require_text templates/verification-manifest.md "Verification Evidence" "verification manifest evidence scaffold"
require_text templates/verification-evidence.md "Draft Path:" "verification evidence draft path scaffold"
require_text templates/verification-evidence.md "Draft SHA256:" "verification evidence draft hash scaffold"
require_text templates/verification-evidence.md "Canon Snapshot SHA256:" "verification evidence canon hash scaffold"
require_text templates/verification-evidence.md "Final Otaku Verdict:" "verification evidence otaku verdict scaffold"
require_text templates/verification-evidence.md "Style Drift Audit:" "verification evidence style scaffold"
require_text templates/verification-evidence.md "Character Voice Audit:" "verification evidence voice scaffold"
require_text templates/verification-evidence.md "Approved Unknowns:" "verification evidence approved unknowns scaffold"
require_text templates/verification-evidence.md "Retcon Approval:" "verification evidence retcon approval scaffold"
require_text templates/verification-evidence.md "Physical Continuity:" "verification evidence physical continuity scaffold"
require_text templates/verification-evidence.md "Possession / Inventory Continuity:" "verification evidence possession continuity scaffold"
require_text templates/verification-evidence.md "Knowledge Boundary Continuity:" "verification evidence knowledge continuity scaffold"
require_text templates/verification-evidence.md "Location / World Rule Continuity:" "verification evidence location world scaffold"
require_text templates/verification-evidence.md "Retcon Safety:" "verification evidence retcon scaffold"
require_text templates/verification-evidence.md "Style Contract Match:" "verification evidence style contract scaffold"
require_text templates/verification-evidence.md "Character Voice Matrix Match:" "verification evidence voice matrix scaffold"
require_text templates/verification-evidence.md "## Evidence Anchors" "verification evidence anchors scaffold"
require_text templates/verification-evidence.md "| Check | Source | Evidence Phrase |" "verification evidence anchors table scaffold"
require_text templates/verification-evidence.md "| Timeline Continuity |" "verification evidence timeline anchor scaffold"
require_text templates/verification-evidence.md "| POV, Diction, and Rhythm Match |" "verification evidence POV anchor scaffold"
require_text templates/verification-evidence.md "| Character Evolution Justification |" "verification evidence character evolution anchor scaffold"
require_text templates/verification-evidence.md "## Ledger Update Anchors" "verification evidence ledger anchors scaffold"
require_text templates/verification-evidence.md "| Ledger Fact | Summary Phrase | Narrative-State Phrase |" "verification evidence ledger anchors table scaffold"
require_text templates/retcon-proposal.md "Status: PENDING" "retcon proposal status scaffold"
require_text templates/retcon-proposal.md "Change Type:" "retcon proposal change type scaffold"
require_text templates/retcon-proposal.md "Decision:" "retcon proposal decision scaffold"
require_text templates/retcon-proposal.md "## Candidate Setting" "retcon proposal candidate setting scaffold"
require_text templates/retcon-proposal.md "Internal Consistency Verdict:" "retcon proposal internal consistency scaffold"
require_text templates/retcon-proposal.md "Prior Narrative Impact Verdict:" "retcon proposal impact verdict scaffold"
require_text templates/retcon-proposal.md "User Approval:" "retcon proposal user approval scaffold"
require_text templates/retcon-proposal.md "Approval Evidence:" "retcon proposal approval evidence scaffold"
require_text templates/retcon-proposal.md "## Impacted Canon Files" "retcon proposal impacted canon scaffold"
require_text templates/retcon-proposal.md "| Canon File | Required Update | Verification Evidence |" "retcon proposal canon table scaffold"
require_text templates/retcon-proposal.md "## Verification Plan" "retcon proposal verification plan scaffold"

require_text install.sh '$TEMPLATE_TARGET/style-guide.md' "bash installer template output"
require_text install.sh '$TEMPLATE_TARGET/character-sheet.md' "bash installer character sheet template output"
require_text install.sh '$TEMPLATE_TARGET/item-sheet.md' "bash installer item sheet template output"
require_text install.sh '$TEMPLATE_TARGET/location-sheet.md' "bash installer location sheet template output"
require_text install.sh '$TEMPLATE_TARGET/world-rule-sheet.md' "bash installer world rule sheet template output"
require_text install.sh '$TEMPLATE_TARGET/writing-session.md' "bash installer writing session template output"
require_text install.sh '$TEMPLATE_TARGET/verification-manifest.md' "bash installer verification manifest output"
require_text install.sh '$TEMPLATE_TARGET/verification-evidence.md' "bash installer verification evidence output"
require_text install.sh '$TEMPLATE_TARGET/retcon-proposal.md' "bash installer retcon proposal output"
require_text install.sh "EPUB build pipeline" "bash installer publisher build label"
require_text install.sh "Installing agents and production templates" "bash installer accurate install message"
require_text install.sh "Human interactive install without git clone" "bash installer clone-free interactive usage"
require_text install.sh 'sh -c "$(curl -sSL https://raw.githubusercontent.com/bbggkkk/opencode-novelist/master/install.sh)"' "bash installer immediate interactive usage"
require_text install.sh "Agent/non-interactive one-line install" "bash installer non-interactive usage"
require_text install.sh './install.sh --project /path/to/project' "bash installer explicit project path usage"
require_text install.sh './install.sh --global' "bash installer global flag usage"
require_text install.sh "PROJECT_DIR" "bash installer project directory support"
require_text install.sh "Project directory:" "bash installer project directory output"
require_text install.sh "GLOBAL_TEMPLATE_TARGET" "bash installer global template target"
require_text install.sh "PROJECT_TEMPLATE_TARGET" "bash installer project template target"
require_text install.sh "GLOBAL_SKILL_TARGET" "bash installer global skill target"
require_text install.sh "PROJECT_SKILL_TARGET" "bash installer project skill target"
require_text install.sh 'rm -rf "$TARGET/templates"' "bash installer removes legacy agent templates"
require_text install.sh 'rm -rf "$TARGET/setting-collapse-detector"' "bash installer removes legacy agent skill"
require_text install.sh "Templates installed outside agent discovery" "bash installer templates outside agent discovery"
require_text install.sh "Skills installed in OpenCode skill discovery" "bash installer skills in skill discovery"
require_text install.sh "skills/setting-collapse-detector/SKILL.md" "bash installer remote skill download"
require_text install.sh "writing-session" "bash installer remote writing session download"
require_text install.sh 'templates/${template}.md' "bash installer remote template download"
require_text install.ps1 '$TemplateTarget/style-guide.md' "powershell installer template output"
require_text install.ps1 '$TemplateTarget/character-sheet.md' "powershell installer character sheet template output"
require_text install.ps1 '$TemplateTarget/item-sheet.md' "powershell installer item sheet template output"
require_text install.ps1 '$TemplateTarget/location-sheet.md' "powershell installer location sheet template output"
require_text install.ps1 '$TemplateTarget/world-rule-sheet.md' "powershell installer world rule sheet template output"
require_text install.ps1 '$TemplateTarget/writing-session.md' "powershell installer writing session template output"
require_text install.ps1 '$TemplateTarget/verification-manifest.md' "powershell installer verification manifest output"
require_text install.ps1 '$TemplateTarget/verification-evidence.md' "powershell installer evidence template output"
require_text install.ps1 '$TemplateTarget/retcon-proposal.md' "powershell installer retcon proposal output"
require_text install.ps1 "EPUB build pipeline" "powershell installer publisher build label"
require_text install.ps1 "Human interactive install without git clone" "powershell installer clone-free interactive usage"
require_text install.ps1 '& ([scriptblock]::Create((irm https://raw.githubusercontent.com/bbggkkk/opencode-novelist/master/install.ps1)))' "powershell installer immediate interactive usage"
require_text install.ps1 "Agent/non-interactive one-line install" "powershell installer non-interactive usage"
require_text install.ps1 '.\install.ps1 --project-dir C:\path\to\project' "powershell installer explicit project path usage"
require_text install.ps1 '.\install.ps1 --global' "powershell installer global flag usage"
require_text install.ps1 "ProjectDir" "powershell installer project directory support"
require_text install.ps1 "Project directory:" "powershell installer project directory output"
require_text install.ps1 "GLOBAL_TEMPLATE_TARGET" "powershell installer global template target"
require_text install.ps1 "PROJECT_TEMPLATE_TARGET" "powershell installer project template target"
require_text install.ps1 "GLOBAL_SKILL_TARGET" "powershell installer global skill target"
require_text install.ps1 "PROJECT_SKILL_TARGET" "powershell installer project skill target"
require_text install.ps1 "LegacyTemplateTarget" "powershell installer removes legacy agent templates"
require_text install.ps1 "LegacySkillTarget" "powershell installer removes legacy agent skill"
require_text install.ps1 "Templates installed outside agent discovery" "powershell installer templates outside agent discovery"
require_text install.ps1 "Skills installed in OpenCode skill discovery" "powershell installer skills in skill discovery"
require_text install.ps1 "skills/setting-collapse-detector/SKILL.md" "powershell installer remote skill download"
require_text install.ps1 "writing-session" "powershell installer remote writing session download"
require_text install.ps1 'templates/$($Template).md' "powershell installer remote template download"
require_text install.ps1 'Test-Path (Join-Path $SCRIPT_DIR "agents")' "powershell local repo detection by agents directory"
require_text install.ps1 "Running from the repository." "powershell local repo message"
require_text Makefile "scripts/validate-all.sh" "make validate entrypoint"
require_text .github/workflows/validate.yml "pull_request:" "CI pull request trigger"
require_text .github/workflows/validate.yml "push:" "CI push trigger"
require_text .github/workflows/validate.yml "make validate" "CI validation command"
require_text .github/workflows/validate.yml "windows-latest" "CI Windows runner"
require_text .github/workflows/validate.yml ".\\install.ps1 --global" "CI PowerShell global installer execution"
require_text .github/workflows/validate.yml ".\\install.ps1 --project-dir" "CI PowerShell project installer execution"
require_text .github/workflows/validate.yml ".config/opencode/novelist/templates" "CI PowerShell template target outside agents"
require_text .github/workflows/validate.yml ".config/opencode/skills" "CI PowerShell skill target in OpenCode discovery"
require_text .github/workflows/validate.yml "Templates must not be installed inside agent discovery path" "CI PowerShell rejects templates under agents"
require_text .github/workflows/validate.yml "Skills must not be installed inside agent discovery path" "CI PowerShell rejects skills under agents"
require_text .github/workflows/validate.yml "novelist-researcher.md" "CI PowerShell researcher install assertion"
require_text .github/workflows/validate.yml "verification-manifest.md" "CI PowerShell template install assertion"
require_text .github/workflows/validate.yml "writing-session.md" "CI PowerShell writing session template install assertion"
require_text .github/workflows/validate.yml "character-sheet.md" "CI PowerShell character sheet install assertion"
require_text .github/workflows/validate.yml "item-sheet.md" "CI PowerShell item sheet install assertion"
require_text .github/workflows/validate.yml "location-sheet.md" "CI PowerShell location sheet install assertion"
require_text .github/workflows/validate.yml "world-rule-sheet.md" "CI PowerShell world rule sheet install assertion"
require_text .github/workflows/validate.yml "verification-evidence.md" "CI PowerShell evidence template install assertion"
require_text .github/workflows/validate.yml "retcon-proposal.md" "CI PowerShell retcon template install assertion"
require_text scripts/validate-all.sh "scripts/validate-agent-frontmatter.sh" "validate-all frontmatter step"
require_text scripts/validate-all.sh "scripts/validate-production-artifacts.sh" "validate-all artifact preflight step"
require_text scripts/validate-all.sh "scripts/test-verification-manifest-negative.sh" "validate-all manifest negative tests step"
require_text scripts/validate-all.sh "scripts/test-production-artifacts-negative.sh" "validate-all artifact negative tests step"
require_text scripts/validate-all.sh "scripts/smoke-install.sh" "validate-all install smoke step"
require_text scripts/validate-sample-work.sh "scripts/validate-verification-manifest.sh" "sample work manifest validator hook"
require_text scripts/smoke-install.sh "templates must not be installed inside agent discovery path" "smoke install rejects agent templates"
require_text scripts/smoke-install.sh "setting-collapse-detector must not be installed inside agent discovery path" "smoke install rejects agent skills"
require_text scripts/smoke-install.sh ".config/opencode/novelist/templates" "smoke install template target outside agents"
require_text scripts/smoke-install.sh ".config/opencode/skills" "smoke install skill target in OpenCode discovery"
require_text scripts/smoke-install.sh './install.sh --global' "smoke install global flag"
require_text scripts/smoke-install.sh './install.sh --project-dir "$tmp_project"' "smoke install explicit project dir"
require_text scripts/smoke-install.sh "project templates must not be installed inside agent discovery path" "smoke install rejects project agent templates"
require_text scripts/validate-production-artifacts.sh "character voice matrix has no completed character rows" "artifact validator voice row check"
require_text scripts/validate-production-artifacts.sh "required style anchors" "artifact validator required style anchors check"
require_text scripts/validate-production-artifacts.sh "forbidden style drift" "artifact validator forbidden style drift check"
require_text scripts/validate-production-artifacts.sh "forbidden literal phrases" "artifact validator forbidden literal phrases check"
require_text scripts/validate-production-artifacts.sh "style verification questions" "artifact validator style verification questions check"
require_text scripts/validate-production-artifacts.sh "style revision guardrails" "artifact validator style revision guardrails check"
require_text scripts/validate-production-artifacts.sh "style POV person" "artifact validator POV person check"
require_text scripts/validate-production-artifacts.sh "style tense" "artifact validator tense check"
require_text scripts/validate-production-artifacts.sh "style viewpoint anchor" "artifact validator viewpoint anchor check"
require_text scripts/validate-production-artifacts.sh "style head-hopping rule" "artifact validator head-hopping check"
require_text scripts/validate-production-artifacts.sh "style-guide Character Voice Matrix header does not match expected schema" "artifact validator voice matrix schema check"
require_text scripts/validate-production-artifacts.sh "character knowledge boundaries" "artifact validator character knowledge boundaries check"
require_text scripts/validate-production-artifacts.sh "character forbidden drift" "artifact validator character forbidden drift check"
require_text scripts/validate-production-artifacts.sh "character active physical anchor" "artifact validator character active physical anchor check"
require_text scripts/validate-production-artifacts.sh "character active inventory anchor" "artifact validator character active inventory anchor check"
require_text scripts/validate-production-artifacts.sh "character active knowledge anchor" "artifact validator character active knowledge anchor check"
require_text scripts/validate-production-artifacts.sh "character habitual expression from voice matrix" "artifact validator voice matrix habitual expression cross-check"
require_text scripts/validate-production-artifacts.sh "character taboo expression from voice matrix" "artifact validator voice matrix taboo expression cross-check"
require_text scripts/validate-production-artifacts.sh "series-bible Chronology header does not match expected schema" "artifact validator series chronology schema check"
require_text scripts/validate-production-artifacts.sh "series-bible Chronology source file missing" "artifact validator series chronology source check"
require_text scripts/validate-production-artifacts.sh "series-bible Chronology evidence phrase missing" "artifact validator chronology evidence missing check"
require_text scripts/validate-production-artifacts.sh "series-bible Chronology evidence phrase not found in source" "artifact validator chronology evidence source check"
require_text scripts/validate-production-artifacts.sh "series-bible Character Evolution Log header does not match expected schema" "artifact validator series evolution schema check"
require_text scripts/validate-production-artifacts.sh "series-bible evolution character missing from Character Voice Matrix" "artifact validator series evolution voice cross-check"
require_text scripts/validate-production-artifacts.sh "series-bible evolution character missing character sheet" "artifact validator series evolution character sheet cross-check"
require_text scripts/validate-production-artifacts.sh "narrative-state Character State header does not match expected schema" "artifact validator character state schema check"
require_text scripts/validate-production-artifacts.sh "narrative-state Location / World Canon References header does not match expected schema" "artifact validator location world schema check"
require_text scripts/validate-production-artifacts.sh "narrative-state Inventory Canon References header does not match expected schema" "artifact validator inventory schema check"
require_text scripts/validate-production-artifacts.sh "active character missing from Character Voice Matrix" "artifact validator active character voice matrix cross-check"
require_text scripts/validate-production-artifacts.sh "active character missing character sheet" "artifact validator active character sheet cross-check"
require_text scripts/validate-production-artifacts.sh "inventory contains trackable possessions" "artifact validator trackable inventory check"
require_text scripts/validate-production-artifacts.sh "Location / World Canon References has no completed rows" "artifact validator location world reference check"
require_text scripts/validate-production-artifacts.sh "location/world canon reference setting file missing" "artifact validator location world setting file check"
require_text scripts/validate-production-artifacts.sh "location/world canon reference missing active constraint" "artifact validator location world constraint check"
require_text scripts/validate-production-artifacts.sh "inventory canon reference setting file missing" "artifact validator item setting file check"
require_text scripts/validate-production-artifacts.sh "inventory item limitations" "artifact validator item limitations check"
require_text scripts/validate-production-artifacts.sh "inventory item current holder value" "artifact validator item holder value check"
require_text scripts/validate-production-artifacts.sh "inventory item active state anchors" "artifact validator item active state anchors check"
require_text scripts/validate-production-artifacts.sh "location active constraints" "artifact validator location active constraints check"
require_text scripts/validate-production-artifacts.sh "location active state anchors" "artifact validator location active state anchors check"
require_text scripts/validate-production-artifacts.sh "world rule statement" "artifact validator world rule statement check"
require_text scripts/validate-production-artifacts.sh "world rule active state anchors" "artifact validator world rule active state anchors check"
require_text scripts/validate-production-artifacts.sh "inventory canon reference holder is not active" "artifact validator item holder check"
require_text scripts/validate-production-artifacts.sh "blank narrative-state field" "artifact validator narrative state blank check"
require_text scripts/validate-production-artifacts.sh "scripts/validate-verification-manifest.sh" "artifact validator manifest hook"
require_text scripts/test-production-artifacts-negative.sh "style placeholder" "artifact negative style placeholder fixture"
require_text scripts/test-production-artifacts-negative.sh "missing forbidden style drift" "artifact negative forbidden style drift fixture"
require_text scripts/test-production-artifacts-negative.sh "missing forbidden literal phrases" "artifact negative forbidden literal phrases fixture"
require_text scripts/test-production-artifacts-negative.sh "missing style verification questions" "artifact negative style verification questions fixture"
require_text scripts/test-production-artifacts-negative.sh "missing head-hopping rule" "artifact negative head-hopping fixture"
require_text scripts/test-production-artifacts-negative.sh "blank character speech" "artifact negative character speech fixture"
require_text scripts/test-production-artifacts-negative.sh "missing character knowledge boundaries" "artifact negative character knowledge boundaries fixture"
require_text scripts/test-production-artifacts-negative.sh "missing character forbidden drift" "artifact negative character forbidden drift fixture"
require_text scripts/test-production-artifacts-negative.sh "missing character active physical anchor" "artifact negative missing character active anchor fixture"
require_text scripts/test-production-artifacts-negative.sh "character active physical anchor not found" "artifact negative broken character active anchor fixture"
require_text scripts/test-production-artifacts-negative.sh "character taboo expression from voice matrix" "artifact negative voice matrix character sheet mismatch fixture"
require_text scripts/test-production-artifacts-negative.sh "narrative state placeholder" "artifact negative narrative state fixture"
require_text scripts/test-production-artifacts-negative.sh "missing character files" "artifact negative missing character fixture"
require_text scripts/test-production-artifacts-negative.sh "active character missing voice matrix row" "artifact negative voice matrix cross-check fixture"
require_text scripts/test-production-artifacts-negative.sh "active character missing character sheet" "artifact negative character sheet cross-check fixture"
require_text scripts/test-production-artifacts-negative.sh "style-guide voice matrix schema drift" "artifact negative voice schema drift fixture"
require_text scripts/test-production-artifacts-negative.sh "series bible chronology schema drift" "artifact negative chronology schema drift fixture"
require_text scripts/test-production-artifacts-negative.sh "series bible chronology source file missing" "artifact negative chronology source fixture"
require_text scripts/test-production-artifacts-negative.sh "series bible chronology evidence phrase missing" "artifact negative chronology evidence missing fixture"
require_text scripts/test-production-artifacts-negative.sh "series bible chronology evidence phrase not found" "artifact negative chronology evidence not found fixture"
require_text scripts/test-production-artifacts-negative.sh "series bible evolution schema drift" "artifact negative evolution schema drift fixture"
require_text scripts/test-production-artifacts-negative.sh "series bible evolution character missing character sheet" "artifact negative evolution orphan fixture"
require_text scripts/test-production-artifacts-negative.sh "location world reference schema drift" "artifact negative location world schema drift fixture"
require_text scripts/test-production-artifacts-negative.sh "character state schema drift" "artifact negative character state schema drift fixture"
require_text scripts/test-production-artifacts-negative.sh "inventory reference schema drift" "artifact negative inventory schema drift fixture"
require_text scripts/test-production-artifacts-negative.sh "missing inventory canon references" "artifact negative inventory references fixture"
require_text scripts/test-production-artifacts-negative.sh "inventory canon reference setting file missing" "artifact negative item setting file fixture"
require_text scripts/test-production-artifacts-negative.sh "inventory item limitations missing" "artifact negative item limitations fixture"
require_text scripts/test-production-artifacts-negative.sh "inventory item current holder value" "artifact negative item holder mismatch fixture"
require_text scripts/test-production-artifacts-negative.sh "inventory canon reference inactive holder" "artifact negative item holder fixture"
require_text scripts/test-production-artifacts-negative.sh "missing location world canon references" "artifact negative location world references fixture"
require_text scripts/test-production-artifacts-negative.sh "location world canon reference setting file missing" "artifact negative location world setting file fixture"
require_text scripts/test-production-artifacts-negative.sh "location active constraints missing" "artifact negative location active constraints fixture"
require_text scripts/test-production-artifacts-negative.sh "location active state anchors missing" "artifact negative location active state anchors fixture"
require_text scripts/test-production-artifacts-negative.sh "world rule statement missing" "artifact negative world rule statement fixture"
require_text scripts/test-production-artifacts-negative.sh "world rule active state anchors not found" "artifact negative world active state anchor fixture"
require_text scripts/test-production-artifacts-negative.sh "location world canon reference missing active constraint" "artifact negative location world constraint fixture"
require_text scripts/validate-verification-manifest.sh "Final Otaku Verdict" "manifest validator verdict check"
require_text scripts/validate-verification-manifest.sh "Draft SHA256" "manifest validator draft hash column check"
require_text scripts/validate-verification-manifest.sh "Canon Snapshot SHA256" "manifest validator canon hash column check"
require_text scripts/validate-verification-manifest.sh "draft SHA256 mismatch" "manifest validator draft hash mismatch check"
require_text scripts/validate-verification-manifest.sh "canon snapshot SHA256 mismatch" "manifest validator canon hash mismatch check"
require_text scripts/validate-verification-manifest.sh "Style Drift Audit" "manifest validator style audit check"
require_text scripts/validate-verification-manifest.sh "Character Voice Audit" "manifest validator voice audit check"
require_text scripts/validate-verification-manifest.sh "Verification Evidence" "manifest validator evidence column check"
require_text scripts/validate-verification-manifest.sh "verification evidence report missing" "manifest validator evidence report existence check"
require_text scripts/validate-verification-manifest.sh "verification evidence draft hash mismatch" "manifest validator evidence draft hash check"
require_text scripts/validate-verification-manifest.sh "verification evidence style drift audit missing PASS" "manifest validator evidence style pass check"
require_text scripts/validate-verification-manifest.sh "verification evidence report must live under verification-reports/" "manifest validator evidence path check"
require_text scripts/validate-verification-manifest.sh "verification evidence report path must stay inside the active volume" "manifest validator evidence traversal check"
require_text scripts/validate-verification-manifest.sh "verification evidence report contains FAIL, PENDING, or UNVERIFIED" "manifest validator contradictory evidence verdict check"
require_text scripts/validate-verification-manifest.sh "verification evidence physical continuity missing PASS" "manifest validator evidence physical continuity check"
require_text scripts/validate-verification-manifest.sh "verification evidence knowledge continuity missing PASS" "manifest validator evidence knowledge continuity check"
require_text scripts/validate-verification-manifest.sh "verification evidence style contract match missing PASS" "manifest validator evidence style contract check"
require_text scripts/validate-verification-manifest.sh "verification evidence voice matrix missing PASS" "manifest validator evidence voice matrix check"
require_text scripts/validate-verification-manifest.sh "verification evidence anchors missing" "manifest validator evidence anchors check"
require_text scripts/validate-verification-manifest.sh "verification evidence required anchor missing" "manifest validator evidence required anchor check"
require_text scripts/validate-verification-manifest.sh "verification evidence anchor phrase not found in source" "manifest validator evidence anchor phrase check"
require_text scripts/validate-verification-manifest.sh "verification evidence anchor source path must stay inside work or volume" "manifest validator evidence anchor traversal check"
require_text scripts/validate-verification-manifest.sh "POV, Diction, and Rhythm Match" "manifest validator evidence POV anchor check"
require_text scripts/validate-verification-manifest.sh "Character Evolution Justification" "manifest validator evidence character evolution anchor check"
require_text scripts/validate-verification-manifest.sh "verification evidence ledger update anchors missing" "manifest validator ledger anchors check"
require_text scripts/validate-verification-manifest.sh "verification evidence required ledger anchor missing" "manifest validator required ledger anchors check"
require_text scripts/validate-verification-manifest.sh "verification evidence ledger summary phrase not found in manifest ledger" "manifest validator ledger summary phrase check"
require_text scripts/validate-verification-manifest.sh "verification evidence ledger state phrase not found in narrative-state" "manifest validator ledger state phrase check"
require_text scripts/validate-verification-manifest.sh "draft has placeholder approved unknowns" "manifest validator approved unknowns placeholder check"
require_text scripts/validate-verification-manifest.sh "verification evidence approved unknowns mismatch" "manifest validator evidence approved unknowns check"
require_text scripts/validate-verification-manifest.sh "Retcon Approval" "manifest validator retcon approval field check"
require_text scripts/validate-verification-manifest.sh "retcon approval file missing" "manifest validator retcon approval existence check"
require_text scripts/validate-verification-manifest.sh "retcon impacted canon file missing on disk" "manifest validator retcon impacted canon existence check"
require_text scripts/validate-verification-manifest.sh "approved unknown is not tracked in narrative-state open hooks" "manifest validator approved unknown open hook check"
require_text scripts/validate-verification-manifest.sh "draft missing from manifest" "manifest validator draft coverage check"
require_text scripts/validate-verification-manifest.sh "duplicate draft entry in manifest" "manifest validator duplicate entry check"
require_text scripts/validate-verification-manifest.sh "manifest lists draft missing on disk" "manifest validator stale entry check"
require_text scripts/validate-verification-manifest.sh "manifest schema header does not match expected column order" "manifest validator schema header check"
require_text scripts/validate-verification-manifest.sh "manifest row has wrong column count" "manifest validator row column count check"
require_text scripts/validate-verification-manifest.sh "draft contains standalone unverified status label" "manifest validator standalone label rejection"
require_text scripts/validate-verification-manifest.sh "draft contains hardcoded leading indentation" "manifest validator draft indentation rejection"
require_text scripts/validate-verification-manifest.sh "draft contains trailing whitespace" "manifest validator draft trailing whitespace rejection"
require_text scripts/validate-verification-manifest.sh "draft contains merge conflict marker" "manifest validator draft merge marker rejection"
require_text scripts/validate-verification-manifest.sh "draft contains raw HTML or unsafe markup" "manifest validator draft raw HTML rejection"
require_text scripts/validate-verification-manifest.sh "draft contains Character Voice Matrix taboo expression" "manifest validator draft taboo expression rejection"
require_text scripts/validate-verification-manifest.sh "draft contains Forbidden Literal Phrase" "manifest validator draft forbidden literal rejection"
require_text scripts/test-verification-manifest-negative.sh "PENDING" "manifest negative pending fixture"
require_text scripts/test-verification-manifest-negative.sh "placeholder approved unknowns" "manifest negative approved unknown placeholder fixture"
require_text scripts/test-verification-manifest-negative.sh "approved unknown is not tracked in narrative-state open hooks" "manifest negative approved unknown hook fixture"
require_text scripts/test-verification-manifest-negative.sh "verification evidence approved unknowns mismatch" "manifest negative evidence approved unknown fixture"
require_text scripts/test-verification-manifest-negative.sh "retcon approval file missing" "manifest negative retcon missing fixture"
require_text scripts/test-verification-manifest-negative.sh "retcon impacted canon file missing on disk" "manifest negative retcon impacted canon fixture"
require_text scripts/test-verification-manifest-negative.sh "extra draft missing from manifest" "manifest negative extra draft fixture"
require_text scripts/test-verification-manifest-negative.sh "duplicate draft manifest entry" "manifest negative duplicate fixture"
require_text scripts/test-verification-manifest-negative.sh "manifest stale draft entry" "manifest negative stale fixture"
require_text scripts/test-verification-manifest-negative.sh "manifest schema header drift" "manifest negative schema drift fixture"
require_text scripts/test-verification-manifest-negative.sh "manifest row wrong column count" "manifest negative row column count fixture"
require_text scripts/test-verification-manifest-negative.sh "unverified standalone draft label" "manifest negative standalone label fixture"
require_text scripts/test-verification-manifest-negative.sh "draft contains hardcoded leading indentation" "manifest negative draft indentation fixture"
require_text scripts/test-verification-manifest-negative.sh "draft contains merge conflict marker" "manifest negative draft merge marker fixture"
require_text scripts/test-verification-manifest-negative.sh "draft contains raw HTML or unsafe markup" "manifest negative draft raw HTML fixture"
require_text scripts/test-verification-manifest-negative.sh "draft contains Character Voice Matrix taboo expression" "manifest negative draft taboo expression fixture"
require_text scripts/test-verification-manifest-negative.sh "draft contains Forbidden Literal Phrase" "manifest negative draft forbidden literal fixture"
require_text scripts/test-verification-manifest-negative.sh "style drift audit failure" "manifest negative style audit fixture"
require_text scripts/test-verification-manifest-negative.sh "character voice audit pending" "manifest negative voice audit fixture"
require_text scripts/test-verification-manifest-negative.sh "draft SHA256 mismatch after mutation" "manifest negative draft mutation fixture"
require_text scripts/test-verification-manifest-negative.sh "canon snapshot SHA256 mismatch after mutation" "manifest negative canon mutation fixture"
require_text scripts/test-verification-manifest-negative.sh "missing verification evidence report" "manifest negative evidence missing fixture"
require_text scripts/test-verification-manifest-negative.sh "verification evidence draft hash mismatch" "manifest negative evidence hash fixture"
require_text scripts/test-verification-manifest-negative.sh "verification evidence style drift audit missing PASS" "manifest negative evidence style fixture"
require_text scripts/test-verification-manifest-negative.sh "verification evidence report outside verification-reports" "manifest negative evidence path fixture"
require_text scripts/test-verification-manifest-negative.sh "verification evidence path traversal" "manifest negative evidence traversal fixture"
require_text scripts/test-verification-manifest-negative.sh "verification evidence report contains FAIL, PENDING, or UNVERIFIED" "manifest negative contradictory evidence fixture"
require_text scripts/test-verification-manifest-negative.sh "verification evidence physical continuity missing PASS" "manifest negative evidence physical fixture"
require_text scripts/test-verification-manifest-negative.sh "verification evidence voice matrix missing PASS" "manifest negative evidence voice matrix fixture"
require_text scripts/test-verification-manifest-negative.sh "verification evidence prose baseline missing PASS" "manifest negative evidence prose fixture"
require_text scripts/test-verification-manifest-negative.sh "verification evidence required anchor missing" "manifest negative evidence anchor missing fixture"
require_text scripts/test-verification-manifest-negative.sh "verification evidence required POV anchor missing" "manifest negative evidence POV anchor missing fixture"
require_text scripts/test-verification-manifest-negative.sh "verification evidence anchor phrase not found in source" "manifest negative evidence anchor phrase fixture"
require_text scripts/test-verification-manifest-negative.sh "verification evidence anchor source path must stay inside work or volume" "manifest negative evidence anchor traversal fixture"
require_text scripts/validate-style-character-drift-scenario.sh "bad internet slang" "style drift scenario slang check"
require_text scripts/validate-style-character-drift-scenario.sh "expected fail verdict" "style drift scenario fail check"
require_text README.md "Revision And Retcon Safety" "README revision safety documentation"
require_text README.md "Canon Expansion Review" "README canon expansion documentation"
require_text README.md "prefers accepting coherent additions" "README canon expansion acceptance bias"
require_text README.md "Draft And Build Pipelines" "README pipeline split documentation"
require_text README.md "Fiction-context research" "README researcher fiction context documentation"
require_text README.md "Interruptible Sessions" "README interruptible sessions documentation"
require_text README.md "writing-session.md" "README writing session documentation"
require_text README.md ".session/current-work.md" "README temporary session work documentation"
require_text README.md "support skills are installed in OpenCode's skill discovery path" "README skill discovery documentation"
require_text README.md "You can also run the interactive installer without cloning the repository first" "README clone-free interactive install documentation"
require_text README.md 'sh -c "$(curl -sSL https://raw.githubusercontent.com/bbggkkk/opencode-novelist/master/install.sh)"' "README bash clone-free installer command"
require_text README.md '& ([scriptblock]::Create((irm https://raw.githubusercontent.com/bbggkkk/opencode-novelist/master/install.ps1)))' "README PowerShell clone-free installer command"
require_text README.md "Single Work Franchise Layout" "README single work franchise layout"
require_text README.md 'Root-level `series-bible.md` is not a valid production layout' "README rejects root series bible layout"
require_text README.md "It does not create EPUB output" "README no automatic EPUB build documentation"
require_text README.md "epub-src/" "README editable EPUB source documentation"
require_text README.md "Canon is never silently retconned" "README no silent retcon documentation"
require_text README.md "make validate" "README full validation entrypoint"
require_text README.md "scripts/validate-all.sh" "README validate-all documentation"
require_text README.md "scripts/validate-sample-work.sh" "README sample work validation documentation"
require_text README.md "scripts/validate-production-artifacts.sh" "README artifact preflight documentation"
require_text README.md "Artifact Preflight Gate" "README artifact preflight gate documentation"
require_text README.md "missing Required Style Anchors" "README required style anchors preflight documentation"
require_text README.md "missing Forbidden Style Drift" "README forbidden style drift preflight documentation"
require_text README.md "missing Style Verification Questions" "README style verification questions preflight documentation"
require_text README.md "missing POV person" "README POV person preflight documentation"
require_text README.md "missing tense" "README tense preflight documentation"
require_text README.md "missing viewpoint anchor" "README viewpoint anchor preflight documentation"
require_text README.md "missing head-hopping rule" "README head-hopping preflight documentation"
require_text README.md "artifact table schema drift" "README artifact schema drift documentation"
require_text README.md "Series Bible chronology source files" "README chronology source documentation"
require_text README.md "Chronology evidence phrases" "README chronology evidence documentation"
require_text README.md "Series Bible evolution characters" "README series evolution cross-check documentation"
require_text README.md "active narrative-state characters" "README artifact active character cross-check documentation"
require_text README.md "voice matrix and character sheet mismatches" "README voice matrix sheet mismatch documentation"
require_text README.md "Inventory Canon References" "README inventory reference documentation"
require_text README.md "Location / World Canon References" "README location world reference documentation"
require_text README.md "verification-manifest.md" "README verification manifest documentation"
require_text README.md "Draft SHA256" "README draft hash documentation"
require_text README.md "Canon Snapshot SHA256" "README canon hash documentation"
require_text README.md "Verification Evidence" "README verification evidence documentation"
require_text README.md "retcon-proposal.md" "README retcon proposal template documentation"
require_text README.md "Retcon Approval" "README retcon approval documentation"
require_text README.md "character-sheet.md" "README character sheet template documentation"
require_text README.md "missing character knowledge boundaries" "README character knowledge boundaries preflight documentation"
require_text README.md "missing forbidden drift guards" "README forbidden drift preflight documentation"
require_text README.md "verification-evidence.md" "README verification evidence template documentation"
require_text README.md "continuity, retcon safety, style, prose baseline, and character voice checklist" "README verification evidence checklist documentation"
require_text README.md "approved unknowns are either" "README approved unknowns documentation"
require_text README.md "Evidence Anchors table covers every checklist item" "README evidence anchors documentation"
require_text README.md "Ledger Update Anchors prove each durable ledger fact" "README ledger anchors documentation"
require_text README.md 'contains no `FAIL`, `PENDING`, or `UNVERIFIED` verdicts' "README contradictory evidence verdict documentation"
require_text README.md "duplicated in the manifest" "README duplicate manifest documentation"
require_text README.md "manifest schema is intact" "README manifest schema documentation"
require_text README.md "Final Otaku Verdict: PASS" "README publisher pass gate documentation"
require_text README.md "Style Drift Audit: PASS" "README style audit pass gate documentation"
require_text README.md "Character Voice Audit: PASS" "README voice audit pass gate documentation"
require_text README.md "hard-indented" "README hard indentation publication gate documentation"
require_text README.md "conflict-marked" "README conflict marker publication gate documentation"
require_text README.md "raw-HTML-contaminated" "README raw HTML publication gate documentation"
require_text README.md "Character Voice Matrix taboo expressions" "README taboo expression publication gate documentation"
require_text README.md "Style Guide Forbidden Literal Phrases" "README forbidden literal publication gate documentation"
require_text README.md "scripts/validate-verification-manifest.sh" "README manifest validator documentation"
require_text README.md "manifest negative tests" "README manifest negative tests documentation"
require_text README.md ".github/workflows/validate.yml" "README CI documentation"
require_text README.md "PowerShell installer" "README PowerShell CI documentation"
require_text README.md "calls are provisional only" "README standalone sub-agent safety documentation"
require_text README.md "UNVERIFIED DRAFT" "README writer standalone label documentation"
require_text README.md "UNVERIFIED REVISION" "README editor standalone label documentation"
require_text README.ko.md "수정 및 설정 변경 안전장치" "Korean README revision safety documentation"
require_text README.ko.md "캐논 확장 검토" "Korean README canon expansion documentation"
require_text README.ko.md "수락하는 쪽을 우선" "Korean README canon expansion acceptance bias"
require_text README.ko.md "초고 / 빌드 파이프라인" "Korean README pipeline split documentation"
require_text README.ko.md "소설 맥락 조사" "Korean README researcher fiction context documentation"
require_text README.ko.md "중단 후 재개 가능 세션" "Korean README interruptible sessions documentation"
require_text README.ko.md "writing-session.md" "Korean README writing session documentation"
require_text README.ko.md ".session/current-work.md" "Korean README temporary session work documentation"
require_text README.ko.md "지원 스킬은 OpenCode의 스킬 탐색 경로에 설치됩니다" "Korean README skill discovery documentation"
require_text README.ko.md "저장소를 먼저 복제하지 않아도 대화형 설치를 실행할 수 있습니다" "Korean README clone-free interactive install documentation"
require_text README.ko.md 'sh -c "$(curl -sSL https://raw.githubusercontent.com/bbggkkk/opencode-novelist/master/install.sh)"' "Korean README bash clone-free installer command"
require_text README.ko.md '& ([scriptblock]::Create((irm https://raw.githubusercontent.com/bbggkkk/opencode-novelist/master/install.ps1)))' "Korean README PowerShell clone-free installer command"
require_text README.ko.md "한 작품 프랜차이즈 구조" "Korean README single work franchise layout"
require_text README.ko.md '루트 바로 아래의 `series-bible.md`는 프로덕션 레이아웃으로 인정하지 않습니다' "Korean README rejects root series bible layout"
require_text README.ko.md "EPUB은 만들지 않습니다" "Korean README no automatic EPUB build documentation"
require_text README.ko.md "epub-src/" "Korean README editable EPUB source documentation"
require_text README.ko.md "make validate" "Korean README full validation entrypoint"
require_text README.ko.md "scripts/validate-sample-work.sh" "Korean README sample work validation documentation"
require_text README.ko.md "scripts/validate-production-artifacts.sh" "Korean README artifact preflight documentation"
require_text README.ko.md "산출물 사전 점검 관문" "Korean README artifact preflight gate documentation"
require_text README.ko.md "누락된 필수 문체 기준점" "Korean README required style anchors preflight documentation"
require_text README.ko.md "누락된 금지 문체 표류" "Korean README forbidden style drift preflight documentation"
require_text README.ko.md "누락된 문체 검증 질문" "Korean README style verification questions preflight documentation"
require_text README.ko.md "누락된 인칭" "Korean README POV person preflight documentation"
require_text README.ko.md "누락된 시제" "Korean README tense preflight documentation"
require_text README.ko.md "누락된 시점 기준점" "Korean README viewpoint anchor preflight documentation"
require_text README.ko.md "누락된 시점 이동 규칙" "Korean README head-hopping preflight documentation"
require_text README.ko.md "산출물 표 스키마 표류" "Korean README artifact schema drift documentation"
require_text README.ko.md "시리즈 바이블 연대기 원본 파일" "Korean README chronology source documentation"
require_text README.ko.md "연대기 증거 문구" "Korean README chronology evidence documentation"
require_text README.ko.md "시리즈 바이블 진화 캐릭터" "Korean README series evolution cross-check documentation"
require_text README.ko.md "character-sheet.md" "Korean README character sheet template documentation"
require_text README.ko.md "음성표와 캐릭터 시트 불일치" "Korean README voice matrix sheet mismatch documentation"
require_text README.ko.md "누락된 캐릭터 지식 경계" "Korean README character knowledge boundaries preflight documentation"
require_text README.ko.md "누락된 금지 표류 안전장치" "Korean README forbidden drift preflight documentation"
require_text README.ko.md "서사 상태 원장의 활성 캐릭터" "Korean README artifact active character cross-check documentation"
require_text README.ko.md "소지품 캐논 참조" "Korean README inventory reference documentation"
require_text README.ko.md "장소/세계관 캐논 참조" "Korean README location world reference documentation"
require_text README.ko.md "verification-manifest.md" "Korean README verification manifest documentation"
require_text README.ko.md "Draft SHA256" "Korean README draft hash documentation"
require_text README.ko.md "Canon Snapshot SHA256" "Korean README canon hash documentation"
require_text README.ko.md "검증 증거 보고서" "Korean README verification evidence documentation"
require_text README.ko.md "retcon-proposal.md" "Korean README retcon proposal template documentation"
require_text README.ko.md "설정 변경 승인" "Korean README retcon approval documentation"
require_text README.ko.md "verification-evidence.md" "Korean README verification evidence template documentation"
require_text README.ko.md "연속성/설정 변경 안전/문체/기본 문장/캐릭터 음성 점검표" "Korean README verification evidence checklist documentation"
require_text README.ko.md "승인된 미확정 사항이" "Korean README approved unknowns documentation"
require_text README.ko.md "증거 기준점 표" "Korean README evidence anchors documentation"
require_text README.ko.md "원장 갱신 기준점" "Korean README ledger anchors documentation"
require_text README.ko.md "실패, 대기, 미검증 판정이 없어야" "Korean README contradictory evidence verdict documentation"
require_text README.ko.md "검증 목록 중복" "Korean README duplicate manifest documentation"
require_text README.ko.md "검증 목록 스키마가 온전" "Korean README manifest schema documentation"
require_text README.ko.md "Style Drift Audit: PASS" "Korean README style audit pass gate documentation"
require_text README.ko.md "Character Voice Audit: PASS" "Korean README voice audit pass gate documentation"
require_text README.ko.md "하드코딩된 들여쓰기" "Korean README hard indentation publication gate documentation"
require_text README.ko.md "충돌 표식" "Korean README conflict marker publication gate documentation"
require_text README.ko.md "원시 HTML" "Korean README raw HTML publication gate documentation"
require_text README.ko.md "캐릭터 음성표 금지 표현" "Korean README taboo expression publication gate documentation"
require_text README.ko.md "문체 가이드 금지 문구" "Korean README forbidden literal publication gate documentation"
require_text README.ko.md "scripts/validate-verification-manifest.sh" "Korean README manifest validator documentation"
require_text README.ko.md "검증 목록 부정 테스트" "Korean README manifest negative tests documentation"
require_text README.ko.md ".github/workflows/validate.yml" "Korean README CI documentation"
require_text README.ko.md "PowerShell 설치 스모크 테스트" "Korean README PowerShell CI documentation"
require_text README.ko.md "직접 호출한 결과는 임시 산출물" "Korean README standalone sub-agent safety documentation"
require_text README.ko.md "UNVERIFIED DRAFT" "Korean README writer standalone label documentation"
require_text README.ko.md "UNVERIFIED REVISION" "Korean README editor standalone label documentation"
require_text docs/agent-design.md "Revision And Retcon Safety" "design revision safety documentation"
require_text docs/agent-design.md "Canon Expansion Review" "design canon expansion documentation"
require_text docs/agent-design.md "default bias is to accept coherent additions" "design canon expansion acceptance bias"
require_text docs/agent-design.md "Draft And Build Pipelines" "design pipeline split documentation"
require_text docs/agent-design.md "fiction-context research for real-world plausibility" "design researcher fiction context documentation"
require_text docs/agent-design.md "support skills are installed in OpenCode skill discovery" "design skill discovery documentation"
require_text docs/agent-design.md "Clone-free interactive install is also supported" "design clone-free interactive install documentation"
require_text docs/agent-design.md "This subdirectory is required even when the franchise currently has only one work" "design requires work subdirectory for single work"
require_text docs/agent-design.md 'Root-level `series-bible.md` is not a valid production layout' "design rejects root series bible layout"
require_text docs/agent-design.md "Build Pipeline" "design build pipeline documentation"
require_text docs/agent-design.md "epub-src/" "design editable EPUB source documentation"
require_text docs/agent-design.md "scripts/validate-all.sh" "design validate-all documentation"
require_text docs/agent-design.md "scripts/validate-production-artifacts.sh" "design artifact preflight documentation"
require_text docs/agent-design.md "Artifact Preflight Gate" "design artifact preflight gate documentation"
require_text docs/agent-design.md "missing Required Style Anchors" "design required style anchors preflight documentation"
require_text docs/agent-design.md "missing Forbidden Style Drift" "design forbidden style drift preflight documentation"
require_text docs/agent-design.md "missing Style Verification Questions" "design style verification questions preflight documentation"
require_text docs/agent-design.md "missing POV person" "design POV person preflight documentation"
require_text docs/agent-design.md "missing tense" "design tense preflight documentation"
require_text docs/agent-design.md "missing viewpoint anchor" "design viewpoint anchor preflight documentation"
require_text docs/agent-design.md "missing head-hopping rule" "design head-hopping preflight documentation"
require_text docs/agent-design.md "artifact table schema drift" "design artifact schema drift documentation"
require_text docs/agent-design.md "missing Series Bible chronology source files" "design chronology source documentation"
require_text docs/agent-design.md "missing Chronology evidence phrases" "design chronology evidence documentation"
require_text docs/agent-design.md "Series Bible evolution characters without matching voice rows or character sheets" "design series evolution cross-check documentation"
require_text docs/agent-design.md "active narrative-state characters without matching Character Voice Matrix rows" "design artifact active character cross-check documentation"
require_text docs/agent-design.md "voice matrix and character sheet mismatches" "design voice matrix sheet mismatch documentation"
require_text docs/agent-design.md "templates/character-sheet.md" "design character sheet template documentation"
require_text docs/agent-design.md "missing character knowledge boundaries" "design character knowledge boundaries preflight documentation"
require_text docs/agent-design.md "missing forbidden drift guards" "design forbidden drift preflight documentation"
require_text docs/agent-design.md "trackable possessions without Inventory Canon References" "design inventory reference documentation"
require_text docs/agent-design.md "active locations or world-rule hooks without Location / World Canon References" "design location world reference documentation"
require_text docs/agent-design.md "Router applies the edit only after Otaku PASS" "design no pre-pass edit application"
require_text docs/agent-design.md "examples/sample-work/" "design sample work fixture documentation"
require_text docs/agent-design.md "Verification Manifest" "design verification manifest documentation"
require_text docs/agent-design.md "Draft SHA256" "design draft hash documentation"
require_text docs/agent-design.md "Canon Snapshot SHA256" "design canon hash documentation"
require_text docs/agent-design.md "Verification Evidence" "design verification evidence documentation"
require_text docs/agent-design.md "Retcon Proposal" "design retcon proposal documentation"
require_text docs/agent-design.md "Retcon Approval" "design retcon approval documentation"
require_text docs/agent-design.md "verification-reports/" "design verification evidence directory documentation"
require_text docs/agent-design.md "physical, possession, knowledge, location/world, timeline, retcon, style, prose baseline, and character voice checklist" "design verification evidence checklist documentation"
require_text docs/agent-design.md "Approved unknowns must be" "design approved unknowns documentation"
require_text docs/agent-design.md "Evidence Anchors" "design evidence anchors documentation"
require_text docs/agent-design.md "Ledger Update Anchors" "design ledger anchors documentation"
require_text docs/agent-design.md 'contradictory `FAIL`, `PENDING`, or `UNVERIFIED` evidence verdicts' "design contradictory evidence verdict documentation"
require_text docs/agent-design.md "hardcoded leading indentation" "design draft indentation publication gate documentation"
require_text docs/agent-design.md "merge conflict markers" "design draft merge marker publication gate documentation"
require_text docs/agent-design.md "raw HTML layout tags" "design draft raw HTML publication gate documentation"
require_text docs/agent-design.md "Character Voice Matrix taboo expressions" "design draft taboo expression publication gate documentation"
require_text docs/agent-design.md "Style Guide Forbidden Literal Phrases" "design draft forbidden literal publication gate documentation"
require_text docs/agent-design.md "appears more than once" "design duplicate manifest documentation"
require_text docs/agent-design.md "manifest schema column order drifts" "design manifest schema documentation"
require_text docs/agent-design.md "Style Drift Audit: PASS" "design style audit pass gate documentation"
require_text docs/agent-design.md "Character Voice Audit: PASS" "design voice audit pass gate documentation"
require_text docs/agent-design.md "validate-verification-manifest.sh" "design manifest validator documentation"
require_text docs/agent-design.md "test-verification-manifest-negative.sh" "design manifest negative tests documentation"
require_text docs/agent-design.md ".github/workflows/validate.yml" "design CI documentation"
require_text docs/agent-design.md "Interruption Recovery" "design interruption recovery documentation"
require_text docs/agent-design.md "writing-session.md" "design writing session documentation"
require_text docs/agent-design.md ".session/" "design temporary session directory documentation"
require_text docs/agent-design.md "UNVERIFIED DRAFT" "design writer standalone safety documentation"
require_text docs/agent-design.md "UNVERIFIED REVISION" "design editor standalone safety documentation"
require_text docs/production-readiness-audit.md "No setting collapse" "readiness audit setting collapse coverage"
require_text docs/production-readiness-audit.md "Preserve requested style" "readiness audit style coverage"
require_text docs/production-readiness-audit.md "Accept safe canon expansion" "readiness audit canon expansion coverage"
require_text docs/production-readiness-audit.md "Resume interrupted work" "readiness audit resume coverage"
require_text docs/production-readiness-audit.md "templates/writing-session.md" "readiness audit writing session template coverage"
require_text docs/production-readiness-audit.md "Required Style Anchors" "readiness audit required style anchors coverage"
require_text docs/production-readiness-audit.md "Forbidden Style Drift" "readiness audit forbidden style drift coverage"
require_text docs/production-readiness-audit.md "Style Verification Questions" "readiness audit style verification questions coverage"
require_text docs/production-readiness-audit.md "Preserve character traits" "readiness audit character coverage"
require_text docs/production-readiness-audit.md "templates/character-sheet.md" "readiness audit character sheet template coverage"
require_text docs/production-readiness-audit.md "voice matrix and character sheet mismatches" "readiness audit voice matrix sheet mismatch coverage"
require_text docs/production-readiness-audit.md "missing character knowledge boundaries" "readiness audit character knowledge boundaries coverage"
require_text docs/production-readiness-audit.md "missing forbidden drift guards" "readiness audit forbidden drift coverage"
require_text docs/production-readiness-audit.md "publication requires" "readiness audit publication gate coverage"
require_text docs/production-readiness-audit.md "Style Drift Audit: PASS" "readiness audit style publication gate coverage"
require_text docs/production-readiness-audit.md "Character Voice Audit: PASS" "readiness audit voice publication gate coverage"
require_text docs/production-readiness-audit.md "validate-style-character-drift-scenario.sh" "readiness audit style drift negative coverage"
require_text docs/production-readiness-audit.md "renowned, seasoned novelist" "readiness audit default prose coverage"
require_text docs/production-readiness-audit.md "Publish only verified drafts" "readiness audit publishing coverage"
require_text docs/production-readiness-audit.md "Draft SHA256" "readiness audit draft hash coverage"
require_text docs/production-readiness-audit.md "Canon Snapshot SHA256" "readiness audit canon hash coverage"
require_text docs/production-readiness-audit.md "Verification Evidence" "readiness audit verification evidence coverage"
require_text docs/production-readiness-audit.md "Separate draft and build pipelines" "readiness audit pipeline split coverage"
require_text docs/production-readiness-audit.md "epub-src/" "readiness audit editable EPUB source coverage"
require_text docs/production-readiness-audit.md "outside agent discovery" "readiness audit templates outside agent discovery coverage"
require_text docs/production-readiness-audit.md "Retcon Approval" "readiness audit retcon approval coverage"
require_text docs/production-readiness-audit.md "templates/retcon-proposal.md" "readiness audit retcon proposal coverage"
require_text docs/production-readiness-audit.md "templates/verification-evidence.md" "readiness audit verification evidence template coverage"
require_text docs/production-readiness-audit.md "checklist PASS for continuity, retcon safety, prose baseline, and character voice" "readiness audit verification evidence checklist coverage"
require_text docs/production-readiness-audit.md "Approved Unknowns that are" "readiness audit approved unknowns coverage"
require_text docs/production-readiness-audit.md "Evidence Anchors for every checklist item" "readiness audit evidence anchors coverage"
require_text docs/production-readiness-audit.md "Ledger Update Anchors proving durable facts" "readiness audit ledger anchors coverage"
require_text docs/production-readiness-audit.md 'no contradictory `FAIL`, `PENDING`, or `UNVERIFIED` evidence verdicts' "readiness audit contradictory evidence coverage"
require_text docs/production-readiness-audit.md "hardcoded leading indentation" "readiness audit draft indentation coverage"
require_text docs/production-readiness-audit.md "merge conflict markers" "readiness audit draft merge marker coverage"
require_text docs/production-readiness-audit.md "raw HTML layout tags" "readiness audit draft raw HTML coverage"
require_text docs/production-readiness-audit.md "Character Voice Matrix taboo expressions" "readiness audit draft taboo expression coverage"
require_text docs/production-readiness-audit.md "Style Guide Forbidden Literal Phrases" "readiness audit draft forbidden literal coverage"
require_text docs/production-readiness-audit.md "appear exactly once" "readiness audit manifest bijection coverage"
require_text docs/production-readiness-audit.md "schema must match the template" "readiness audit manifest schema coverage"
require_text docs/production-readiness-audit.md "Block weak starting canon" "readiness audit artifact preflight coverage"
require_text docs/production-readiness-audit.md "validate-production-artifacts.sh" "readiness audit artifact validator coverage"
require_text docs/production-readiness-audit.md "artifact table schema drift" "readiness audit artifact schema drift coverage"
require_text docs/production-readiness-audit.md "missing chronology sources" "readiness audit chronology source coverage"
require_text docs/production-readiness-audit.md "missing Chronology evidence phrases" "readiness audit chronology evidence coverage"
require_text docs/production-readiness-audit.md "Series Bible evolution characters" "readiness audit series evolution cross-check coverage"
require_text docs/production-readiness-audit.md "cross-checks active narrative-state plus Series Bible evolution characters" "readiness audit artifact cross-check coverage"
require_text docs/production-readiness-audit.md "inventory canon references" "readiness audit inventory reference coverage"
require_text docs/production-readiness-audit.md "location/world canon references" "readiness audit location world reference coverage"
require_text docs/production-readiness-audit.md "make validate" "readiness audit release gate"
require_text docs/model-recommendations.md "General Selection Policy" "model recommendations general policy"
require_text docs/model-recommendations.md "deepseek v4 flash" "model recommendations deepseek example"
require_text docs/model-recommendations.md "gemma 4 31b" "model recommendations gemma example"
require_text docs/model-recommendations.md "novelist-writer" "model recommendations writer section"
require_text docs/model-recommendations.md "novelist-editor" "model recommendations editor section"
require_text docs/model-recommendations.md "novelist-otaku" "model recommendations otaku section"
require_text docs/model-recommendations.md "Practical Assignment Matrix" "model recommendations assignment matrix"
require_text docs/model-recommendations.md "Korean version" "model recommendations Korean version link"
require_text docs/model-recommendations.ko.md "일반 선택 원칙" "Korean model recommendations general policy heading"
require_text docs/model-recommendations.ko.md "아키텍처 이름보다 역할 적합성을 우선합니다" "Korean model recommendations general policy"
require_text docs/model-recommendations.ko.md "deepseek v4 flash" "Korean model recommendations deepseek example"
require_text docs/model-recommendations.ko.md "gemma 4 31b" "Korean model recommendations gemma example"
require_text docs/model-recommendations.ko.md "novelist-writer" "Korean model recommendations writer section"
require_text docs/model-recommendations.ko.md "novelist-editor" "Korean model recommendations editor section"
require_text docs/model-recommendations.ko.md "novelist-otaku" "Korean model recommendations otaku section"
require_text docs/model-recommendations.ko.md "실전 배정표" "Korean model recommendations assignment matrix"
require_text docs/model-recommendations.ko.md "세부 요구사항:" "Korean model recommendations detailed requirements"
require_text docs/model-recommendations.ko.md "추천 모델 프로필:" "Korean model recommendations model profile"
require_text docs/agent-design.md "windows-latest" "design Windows CI documentation"

reject_text "Done & Publish|완료 및 출판|Full loop & publishing|compile final consolidated draft into EPUB|EPUB book compiler|epub_temp|rm -rf epub_temp|Always run the full loop, compile" "deprecated coupled draft/build pipeline wording remains"
reject_text 'cp -r templates .*opencode/agents|cp -r templates .*\.opencode/agents|Join-Path \$Target "templates"|TARGET/templates/style-guide|setting-collapse-detector/SKILL\.md" \] \|\| fail|Join-Path \$Target "setting-collapse-detector"|agents/setting-collapse-detector/SKILL\.md' "template or skill install path under agent discovery remains"
reject_text "Standalone Work Layout|Isomorphic Fallback|root acts as both|Standalone mode|standalone mode|single standalone work|프랜차이즈 겸 작품|1단계 & 2단계 통합|단독 작품 구조" "deprecated root-as-work standalone layout wording remains"
reject_text "Research & LaTeX paper writing|Research scientist: analyzes project context|writes LaTeX papers|paper, latex, experiment|LaTeX paper from|LaTeX 논문" "deprecated researcher academic-paper role remains"
reject_text "Author/Person Imitation|Style & Imitation|style imitation targets|emulate the prose style|request to emulate|문체 모사|작가/인물 모방|모방 타깃|흉내 내도록|무라카미|하루키|김영하|opencode-agent-pack" "deprecated direct-imitation wording, named-author example, or old repository name remains"

scripts/validate-continuity-scenario.sh
scripts/validate-style-character-drift-scenario.sh
scripts/validate-sample-work.sh
scripts/validate-production-artifacts.sh

printf 'production invariants ok\n'
